"""Convert a local photo into flash-resident RGB565 pixels for the CYD.

Run from any directory: python convert_image.py "path/to/photo.jpg"
Requires Pillow. Outputs are relative to this script's firmware directory.
"""

import argparse
from pathlib import Path

from PIL import Image, ImageOps


def rgb565(red, green, blue):
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def convert(source):
    firmware = Path(__file__).resolve().parents[1]
    assets = firmware / "assets"
    assets.mkdir(exist_ok=True)
    with Image.open(source) as original:
        oriented = ImageOps.exif_transpose(original)
        # Flatten transparent PNGs onto black, and preserve the entire composition.
        rgba = oriented.convert("RGBA")
        background = Image.new("RGBA", rgba.size, (0, 0, 0, 255))
        background.alpha_composite(rgba)
        photo = ImageOps.contain(background.convert("RGB"), (320, 240),
                                Image.Resampling.LANCZOS)
        original_size = oriented.size

    width, height = photo.size
    rgb_bytes = photo.tobytes()
    pixels = [rgb565(*rgb_bytes[i:i + 3]) for i in range(0, len(rgb_bytes), 3)]
    header = firmware / "include" / "photo_rgb565.h"
    with header.open("w", encoding="utf-8", newline="\n") as output:
        output.write("// Generated by tools/convert_image.py; do not edit pixel values.\n")
        output.write("// Native RGB565 words: use tft.setSwapBytes(true).\n")
        output.write("#pragma once\n#include <Arduino.h>\n\nnamespace photo {\n")
        output.write(f"constexpr int16_t kWidth = {width};\n")
        output.write(f"constexpr int16_t kHeight = {height};\n")
        output.write("alignas(4) const uint16_t kPixels[] PROGMEM = {\n")
        for start in range(0, len(pixels), 12):
            output.write("    " + ", ".join(f"0x{p:04X}" for p in pixels[start:start + 12]) + ",\n")
        output.write("};\nstatic_assert(sizeof(kPixels) / sizeof(kPixels[0]) == "
                     "kWidth * kHeight, \"Photo pixel count mismatch\");\n")
        output.write("}  // namespace photo\n")

    # Preview the actual quantized pixel values, with the same black margins.
    quantized = Image.new("RGB", (width, height))
    quantized.putdata([(((p >> 11) & 31) * 255 // 31,
                        ((p >> 5) & 63) * 255 // 63,
                        (p & 31) * 255 // 31) for p in pixels])
    preview = Image.new("RGB", (320, 240), "black")
    preview.paste(quantized, ((320 - width) // 2, (240 - height) // 2))
    preview.save(assets / "photo_preview.png")
    print(f"Source: {original_size[0]} x {original_size[1]}")
    print(f"Photo: {width} x {height}; RGB565: {len(pixels) * 2:,} bytes in flash")
    print(f"Header: {header}")
    print(f"Preview: {assets / 'photo_preview.png'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    convert(parser.parse_args().source)
